include:
 - project: 'grandlinex/templates'
   file: '/stages.yml'
 - project: 'grandlinex/templates'
   file: '/prod/electron-bundle.yml'
 - project: 'grandlinex/templates'
   file: '/build/electron-bundle.yml'
 - project: 'grandlinex/templates'
   file: '/sonar/electron-sonar.yml'
 - project: 'grandlinex/templates'
   file: '/deploy/npm-deploy.yml'
 - project: 'grandlinex/templates'
   file: '/update/update-glx.yml'
 - project: 'grandlinex/templates'
   file: '/deploy/npm-gitlab-deploy.yml'
 - project: 'grandlinex/templates'
   file: '/test/sast.yml'
 - project: 'grandlinex/templates'
   file: '/trigger/public-electron.yml'
 - project: 'grandlinex/templates'
   file: '/trigger/electron-skeleton.yml'
